function(soupmix_enable_sanitizers target)
    if(NOT (CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU"))
        return()
    endif()

    set(_sanitizers "")
    if(SOUPMIX_ENABLE_ASAN)
        list(APPEND _sanitizers "address")
    endif()
    if(SOUPMIX_ENABLE_UBSAN)
        list(APPEND _sanitizers "undefined")
    endif()

    if(_sanitizers)
        list(JOIN _sanitizers "," _flags)
        target_compile_options(${target} INTERFACE -fsanitize=${_flags} -fno-omit-frame-pointer)
        target_link_options(${target} INTERFACE -fsanitize=${_flags})
    endif()
endfunction()
