# Project version. Single source of truth.
set(SOUPMIX_VERSION_MAJOR 0)
set(SOUPMIX_VERSION_MINOR 1)
set(SOUPMIX_VERSION_PATCH 0)
set(SOUPMIX_VERSION
    "${SOUPMIX_VERSION_MAJOR}.${SOUPMIX_VERSION_MINOR}.${SOUPMIX_VERSION_PATCH}")
